//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWIZELL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlquilerHist
    {
        public int IdAlquiler { get; set; }
        public string UserId { get; set; }
        public int IdJuego { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaEntrega { get; set; }
    }
}
